package com.av.urbanway.data.service

import com.av.urbanway.data.model.QueryType
import com.av.urbanway.data.parser.QueryParser
import com.av.urbanway.data.repository.ChatRepository
import java.time.LocalDateTime

class ChatService(
    private val chatRepository: ChatRepository,
    private val queryParser: QueryParser,
    private val dataService: HardcodedDataService
) {

    suspend fun handleUserInput(userInput: String) {
        // Step 1: Add user message
        chatRepository.addUserMessage(userInput)

        // Step 2: Parse the query
        val queryType = queryParser.parseUserInput(userInput)

        if (queryType == null) {
            // Handle unknown query
            handleUnknownQuery(userInput)
            return
        }

        // Step 3: Add autogenerated message
        val autogeneratedText = queryParser.generateAutogeneratedText(userInput, queryType)
        chatRepository.addAutogeneratedMessage(autogeneratedText, queryType)

        // Step 4: Get data and add bot response
        when (queryType) {
            QueryType.NEARBY -> handleNearbyQuery(userInput)
            QueryType.ROUTEDETAIL -> handleRouteDetailQuery(userInput)
            QueryType.STOPDETAIL -> handleStopDetailQuery(userInput)
            QueryType.JOURNEY -> handleJourneyQuery(userInput)
        }
    }

    private fun handleNearbyQuery(userInput: String) {
        val nearbyData = dataService.getNearbyArrivals()

        // Count unique routes from arrivals
        val uniqueRoutes = nearbyData.arrivals.map { it.routeName }.toSet().size
        val totalStops = nearbyData.stops.size

        val botResponse = "Da qui passano $uniqueRoutes linee e hai $totalStops fermate disponibili"

        chatRepository.addBotMessage(
            content = botResponse,
            queryType = QueryType.NEARBY,
            data = nearbyData,
            isCompact = false
        )
    }

    private fun handleRouteDetailQuery(userInput: String) {
        // TODO: Implement when you provide ROUTEDETAIL JSON
        val botResponse = queryParser.generateBotResponse(QueryType.ROUTEDETAIL, userInput)
        // For now, create empty data - will be replaced with real data later
    }

    private fun handleStopDetailQuery(userInput: String) {
        // TODO: Implement when you provide STOPDETAIL JSON
        val botResponse = queryParser.generateBotResponse(QueryType.STOPDETAIL, userInput)
        // For now, create empty data - will be replaced with real data later
    }

    private fun handleJourneyQuery(userInput: String) {
        // TODO: Implement when you provide JOURNEY JSON
        val botResponse = queryParser.generateBotResponse(QueryType.JOURNEY, userInput)
        // For now, create empty data - will be replaced with real data later
    }

    private fun handleUnknownQuery(userInput: String) {
        chatRepository.addBotMessage(
            content = "Non ho capito la tua richiesta. Prova a chiedere informazioni su arrivi, linee o percorsi.",
            queryType = QueryType.NEARBY, // Default fallback
            data = dataService.getNearbyArrivals(),
            isCompact = false
        )
    }

    fun handleModalSelection(selectedRoute: String, fromQueryType: QueryType) {
        when (fromQueryType) {
            QueryType.NEARBY -> {
                // User selected a route from nearby results
                // This should trigger ROUTEDETAIL query
                val routeData = getRouteDetailData(selectedRoute)
                chatRepository.handleModalSelection(
                    selectedItem = "Linea $selectedRoute",
                    fromQueryType = QueryType.NEARBY,
                    newData = routeData
                )
            }
            else -> {
                // Handle other modal selections
            }
        }
    }

    private fun getRouteDetailData(routeId: String): com.av.urbanway.data.model.TransitData {
        // TODO: Return actual route detail data when JSON is provided
        // For now return nearby data as placeholder
        return dataService.getNearbyArrivals()
    }
}