package com.av.urbanway.data.model

import java.time.LocalDateTime

enum class MessageType {
    USER,
    AUTOGENERATED,
    BOT
}

enum class QueryType {
    NEARBY,
    ROUTEDETAIL,
    STOPDETAIL,
    JOURNEY
}

data class ChatMessage(
    val id: String,
    val type: MessageType,
    val content: String,
    val queryType: QueryType? = null,
    val data: TransitData? = null,
    val isCompact: Boolean = false,
    val lastUpdated: LocalDateTime,
    val timestamp: LocalDateTime = LocalDateTime.now()
)

sealed class TransitData {
    data class NearbyData(
        val stops: List<Stop>,
        val arrivals: List<Arrival>
    ) : TransitData()

    data class RouteDetailData(
        val route: Route,
        val stops: List<RouteStop>,
        val shapes: List<ShapePoint>
    ) : TransitData()

    data class StopDetailData(
        val stop: Stop,
        val arrivals: List<Arrival>,
        val routes: List<Route>
    ) : TransitData()

    data class JourneyData(
        val origin: Location,
        val destination: Location,
        val routes: List<JourneyRoute>,
        val duration: Int,
        val walkingTime: Int
    ) : TransitData()
}

data class Stop(
    val id: String,
    val name: String,
    val location: Location,
    val routes: List<String>
)

data class RouteStop(
    val stopId: String,
    val stopCode: String,
    val stopName: String,
    val arrivalDate: Int,
    val stopLat: Double,
    val stopLon: Double
)

data class ShapePoint(
    val shapePtLat: Double,
    val shapePtLon: Double
)

data class Route(
    val id: String,
    val name: String,
    val type: TransportType,
    val color: String,
    val direction: String
)

data class Arrival(
    val routeId: String,
    val routeName: String,
    val direction: String,
    val scheduledTime: LocalDateTime,
    val realTimeMinutes: Int,
    val isRealTime: Boolean
)

data class Location(
    val latitude: Double,
    val longitude: Double,
    val address: String? = null
)

data class JourneyRoute(
    val steps: List<JourneyStep>,
    val totalDuration: Int,
    val totalWalking: Int
)

data class JourneyStep(
    val type: StepType,
    val route: Route? = null,
    val fromStop: Stop? = null,
    val toStop: Stop? = null,
    val duration: Int,
    val walkingDistance: Int? = null
)

data class RealTimeUpdate(
    val routeId: String,
    val delay: Int,
    val status: String,
    val lastUpdated: LocalDateTime
)

enum class TransportType {
    BUS,
    TRAM,
    METRO,
    TRAIN
}

enum class StepType {
    WALK,
    BUS,
    TRAM,
    METRO,
    TRAIN
}